services:
  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py seed && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A remotereps worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A remotereps beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:8.0.1-alpine
    ports:
      - "6379:6379"
