# Generated by Django 5.2.1 on 2025-05-15 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('monthly_budget', models.IntegerField(default=0)),
                ('daily_budget', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField()),
                ('start_hour', models.IntegerField(default=0)),
                ('end_hour', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgettracker.brand')),
            ],
        ),
        migrations.CreateModel(
            name='DailySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('amount_spent', models.IntegerField(default=0)),
                ('Campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgettracker.brand')),
            ],
        ),
    ]
