# Generated by Django 5.2.1 on 2025-05-15 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyspend',
            name='Campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyspends', to='budgettracker.campaign'),
        ),
    ]
