# Generated by Django 5.2.1 on 2025-05-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker', '0002_alter_dailyspend_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyspend',
            old_name='Campaign',
            new_name='campaign',
        ),
    ]
