# Generated by Django 5.2.1 on 2025-05-16 01:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker', '0003_rename_campaign_dailyspend_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dailyspend',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
