# Generated by Django 5.2.1 on 2025-05-16 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker', '0004_alter_brand_created_date_alter_campaign_created_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyspend',
            unique_together={('campaign', 'created_date')},
        ),
    ]
